import { st, rect, click, drag, rclick, key, sleep, check, ev, shot, wheel, move } from '../drive.mjs'
await ev(`__ove.store.setState({clips:[],past:[],future:[],selection:[],zoom:60,playhead:0})`)
const media = Object.values(await st('s.media'))
const short = media.find((m) => m.name === '2026-09-15 01-52-36.mkv'), long = media.find((m) => m.name === '2023-08-16 23-55-20.mp4')
const binItem = (m) => rect(`[data-media="${m.id}"]`)
const rowY = async (t) => { const r = await rect(`[data-track="${t}"]`); return r.y + r.h / 2 }
const laneX = async (t) => (await rect('.lane')).x + t * (await st('s.zoom'))
const clips = () => st('s.clips')
let b = await binItem(long); await drag(b.x + 40, b.y + 20, await laneX(0) + 5, await rowY('V1'))
check('drag bin->V1 creates video+audio clips', (await clips()).length === 2)
// fit the whole 7:54 into the window
await ev(`__ove.store.getState().setZoom(2.8)`); await sleep(200)
b = await binItem(short); await drag(b.x + 40, b.y + 20, await laneX(480), await rowY('V1'))
const sv = (await clips()).find((c) => c.mediaId === short.id && c.kind === 'video')
check('short clip dropped after long one', !!sv && Math.abs(sv.start - 480) < 4, sv && sv.start.toFixed(1))
await ev(`__ove.store.getState().setSelection([])`)
let tc = await rect(`[data-clip="${sv.id}"]`); console.log('  tiny clip width px', tc.w.toFixed(1))
await click(tc.x + tc.w / 2, tc.y + tc.h / 2)
check('click tiny clip centre selects it', (await st('s.selection')).includes(sv.id))
await shot('D:\\ove-test\\cache\\tiny.png')
await ev(`__ove.store.getState().setSelection([])`)
await click(tc.x + 1, tc.y + tc.h / 2)
check('click tiny clip left edge selects it', (await st('s.selection')).includes(sv.id))
await ev(`__ove.store.getState().setSelection([])`)
await click(tc.x + tc.w - 1, tc.y + tc.h / 2)
check('click tiny clip right edge selects it', (await st('s.selection')).includes(sv.id))
const a2 = (await clips()).find((c) => c.id === sv.id)
check('edge clicks did not change clip', Math.abs(a2.dur - sv.dur) < 1e-6 && Math.abs(a2.start - sv.start) < 1e-6)
const insp = await ev(`document.querySelector('.inspector .ptitle').textContent`)
check('inspector shows selected clip', /video/.test(insp), insp)
// overwrite: drag short over the middle of long
await ev(`__ove.store.getState().setZoom(2.8)`)
const before = await clips(); const lv = before.find((c) => c.mediaId === long.id && c.kind === 'video')
tc = await rect(`[data-clip="${sv.id}"]`)
await drag(tc.x + tc.w / 2, tc.y + tc.h / 2, (await laneX(200)) + tc.w / 2, tc.y + tc.h / 2)
let after = (await clips()).filter((c) => c.trackId === 'V1').sort((a, b) => a.start - b.start)
console.log('  V1 after overwrite:', JSON.stringify(after.map((c) => [c.start.toFixed(2), (c.start + c.dur).toFixed(2), c.mediaId === short.id ? 'short' : 'long', c.in.toFixed(2)])))
let ov = after.some((c, i) => i && c.start < after[i - 1].start + after[i - 1].dur - 1e-3)
check('drag B over A: no overlap on V1, A split around B', !ov && after.length === 3)
{ const au = (await clips()).filter((c) => c.trackId === 'A1').sort((a, b) => a.start - b.start); check('audio A1 also split, no overlap', au.length === 3 && !au.some((c, i) => i && c.start < au[i - 1].start + au[i - 1].dur - 1e-3), au.length + ' clips') }
await key('z', ['ctrl'])
after = (await clips()).filter((c) => c.trackId === 'V1')
check('Ctrl+Z restores A (single long + short back at 480)', after.length === 2 && after.find((c) => c.mediaId === long.id).dur > 474, JSON.stringify(after.map((c) => [c.start, c.dur])))
await key('z', ['ctrl', 'shift'])
check('Ctrl+Shift+Z redoes overwrite', (await clips()).filter((c) => c.trackId === 'V1').length === 3)
await key('z', ['ctrl'])
// ctrl+wheel zoom
const z0 = await st('s.zoom'); await wheel(600, 700, -100); await sleep(100)
check('Ctrl+wheel zooms timeline', (await st('s.zoom')) > z0, `${z0} -> ${await st('s.zoom')}`)
await ev(`__ove.store.getState().setZoom(2.8)`)
// bin removal
const nMedia = Object.keys(await st('s.media')).length
const m3 = media[3]; b = await binItem(m3); await click(b.x + 100, b.y + 20)
check('click bin item selects it', (await st('s.binSel')).includes(m3.id))
await key('Delete')
check('Delete removes selected bin item', Object.keys(await st('s.media')).length === nMedia - 1)
await key('z', ['ctrl'])
check('Ctrl+Z brings bin item back', Object.keys(await st('s.media')).length === nMedia)
// remove item in use via × button
b = await binItem(short); await click(b.x + b.w - 12, b.y + 12)
const used = await st('[Object.keys(s.media).length, s.clips.filter(c=>c.mediaId).length, s.status]')
check('× on in-use item removes item and its clips, tells user', used[0] === nMedia - 1 && used[1] === 2 && /timeline clip/.test(used[2]), used[2])
await key('z', ['ctrl'])
check('undo restores item and clips', Object.keys(await st('s.media')).length === nMedia && (await clips()).length === 4)
// context menu
b = await binItem(m3); await rclick(b.x + 100, b.y + 20); await sleep(100)
check('context menu appears', !!(await rect('.ctx')))
const cm = await rect('.ctx div:nth-child(2)'); await click(cm.x + 10, cm.y + 5)
check('context menu Remove works', Object.keys(await st('s.media')).length === nMedia - 1)
await key('z', ['ctrl'])
await shot('D:\\ove-test\\cache\\core-end.png')
