import { st, rect, click, drag, key, sleep, check, ev, shot, typeText, tripleClick } from '../drive.mjs'
const media = Object.values(await st('s.media'))
const A = media.find((m) => m.name.startsWith('2021-04-11 15-00-15'))
const clips = () => st('s.clips')
await ev(`__ove.store.setState({clips:[],past:[],future:[],selection:[],zoom:100,playhead:0,tool:'select'})`)
const b0 = await rect(`[data-media="${A.id}"]`); const rY = (await rect('[data-track="V1"]'))
const lane = await rect('.lane')
await drag(b0.x + 40, b0.y + 20, lane.x + 3, rY.y + rY.h / 2)
await drag(b0.x + 40, b0.y + 20, lane.x + 3 + 360, rY.y + rY.h / 2)
let cs = (await clips()).filter((c) => c.kind === 'video').sort((a, b) => a.start - b.start)
check('two adjacent V1 clips', cs.length === 2 && Math.abs(cs[1].start - cs[0].start - cs[0].dur) < 0.2, cs.map((c) => c.start.toFixed(2)).join(','))
const pick = async (c) => { const r = await rect(`[data-clip="${c.id}"]`); await click(r.x + r.w / 2, r.y + r.h / 2) }
await pick(cs[1])
const fields = async () => JSON.parse(await ev(`JSON.stringify([...document.querySelectorAll('.insp .num')].map(l=>{const i=l.querySelector('input[type=range]');const n=l.querySelector('input[type=number]');const a=i?i.getBoundingClientRect():{};const b=n.getBoundingClientRect();return {label:l.querySelector('span').textContent,r:{x:a.x,y:a.y,w:a.width,h:a.height},n:{x:b.x,y:b.y,w:b.width,h:b.height}}}))`))
let L = await fields(); const f = (n) => L.find((l) => l.label === n)
await click(f('Brightness').r.x + f('Brightness').r.w * 0.75, f('Brightness').r.y + f('Brightness').r.h / 2)
let c1 = (await clips()).find((c) => c.id === cs[1].id)
check('click on Brightness slider sets ~1.5', Math.abs(c1.brightness - 1.5) < 0.12, c1.brightness)
await drag(f('Contrast').r.x + f('Contrast').r.w / 2, f('Contrast').r.y + 8, f('Contrast').r.x + 10, f('Contrast').r.y + 8)
c1 = (await clips()).find((c) => c.id === cs[1].id); check('drag Contrast slider to left lowers it', c1.contrast < 0.3, c1.contrast)
await tripleClick(f('Saturation').n.x + 10, f('Saturation').n.y + 8); await typeText('0.5'); await key('Tab')
c1 = (await clips()).find((c) => c.id === cs[1].id); check('type 0.5 into Saturation number', Math.abs(c1.saturation - 0.5) < 0.01, c1.saturation)
await tripleClick(f('Scale').n.x + 10, f('Scale').n.y + 8); await typeText('1.5'); await key('Tab')
c1 = (await clips()).find((c) => c.id === cs[1].id); check('type 1.5 into Scale', Math.abs(c1.scale - 1.5) < 0.01, c1.scale)
await tripleClick(f('Crop left').n.x + 10, f('Crop left').n.y + 8); await typeText('0.2'); await key('Tab')
c1 = (await clips()).find((c) => c.id === cs[1].id); check('type 0.2 into Crop left', Math.abs(c1.crop.l - 0.2) < 0.01, JSON.stringify(c1.crop))
// speed
await tripleClick(f('Speed').n.x + 10, f('Speed').n.y + 8); await typeText('2'); await key('Tab')
const spd = (await clips()).filter((c) => c.link === c1.link)
check('Speed 2 halves duration on video AND linked audio', spd.length === 2 && spd.every((c) => c.speed === 2 && Math.abs(c.dur - 1.792) < 0.05), JSON.stringify(spd.map((c) => [c.kind, c.speed, c.dur])))
await ev(`document.activeElement.blur()`)
// undo each by keyboard: Ctrl+Z steps
await key('z', ['ctrl']); await key('z', ['ctrl']); 
c1 = (await clips()).find((c) => c.id === cs[1].id); check('Ctrl+Z undoes inspector edits stepwise', c1.speed === 1, `speed ${c1.speed} scale ${c1.scale}`)
// dissolve button
const btn = async (text) => JSON.parse(await ev(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.includes(${JSON.stringify(text)}));if(!b)return 'null';b.scrollIntoView();const r=b.getBoundingClientRect();return JSON.stringify({x:r.x,y:r.y,w:r.width,h:r.height})})()`))
await pick(cs[1])
let d = await btn('Cross-dissolve'); await click(d.x + 10, d.y + 8)
c1 = (await clips()).find((c) => c.id === cs[1].id); check('Cross-dissolve button adds transition', c1.transition > 0, `transition ${c1.transition}`)
// + Title via toolbar button
const tb = await btn('+ Title'); await click(tb.x + 10, tb.y + 8)
const tt = (await clips()).find((c) => c.kind === 'title'); check('+ Title adds a title clip and selects it', !!tt && (await st('s.selection'))[0] === tt.id)
await sleep(300)
const ta = JSON.parse(await ev(`(()=>{const t=document.querySelector('.insp textarea').getBoundingClientRect();return JSON.stringify({x:t.x,y:t.y})})()`))
await tripleClick(ta.x + 20, ta.y + 10); await key('a', ['ctrl']); await typeText('Hello Jaxon')
check('typing in title textarea changes text', (await clips()).find((c) => c.id === tt.id).text.includes('Hello'), (await clips()).find((c) => c.id === tt.id).text)
await ev(`document.activeElement.blur()`)
// audio: select audio clip, fade/volume
const au = (await clips()).find((c) => c.kind === 'audio'); await pick(au)
L = await fields(); await tripleClick(f('Fade in').n.x + 10, f('Fade in').n.y + 8); await typeText('0.5'); await key('Tab')
check('Fade in set', Math.abs((await clips()).find((c) => c.id === au.id).fadeIn - 0.5) < 0.01)
await ev(`__ove.engine.seek(1)`)
const kb = await btn('Add keyframe at playhead'); await click(kb.x + 10, kb.y + 8)
check('Add keyframe at playhead', (await clips()).find((c) => c.id === au.id).keys.length === 1)
await shot('D:\\ove-test\\cache\\inspector.png')
